//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Mavlink.Shell {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Mavlink.Shell.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input date/time value.
        /// </summary>
        public static string DialogsApi_ask_date_time_Please_input_date_time_value {
            get {
                return ResourceManager.GetString("DialogsApi_ask_date_time_Please_input_date_time_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input double value.
        /// </summary>
        public static string DialogsApi_ask_double_Please_input_double_value {
            get {
                return ResourceManager.GetString("DialogsApi_ask_double_Please_input_double_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input integer value.
        /// </summary>
        public static string DialogsApi_ask_integer_Please_input_integer_value {
            get {
                return ResourceManager.GetString("DialogsApi_ask_integer_Please_input_integer_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input only &apos;y&apos;=yes or &apos;n&apos;=no char.
        /// </summary>
        public static string DialogsApi_ask_yes_no {
            get {
                return ResourceManager.GetString("DialogsApi_ask_yes_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be from 0.0 (0 %) to 1.0 (100%).
        /// </summary>
        public static string TextRender_Progress_OutOfRange {
            get {
                return ResourceManager.GetString("TextRender_Progress_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mast be more then {1}.
        /// </summary>
        public static string TextRender_Progress_WidthError {
            get {
                return ResourceManager.GetString("TextRender_Progress_WidthError", resourceCulture);
            }
        }
    }
}
