using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text;
using System.Globalization;
using System.IO;

namespace Asv.Mavlink.Shell;

public class ArduPilotMotorsLayoutGenerator
{
	public static void Generate()
	{
		CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;

		var jsonPath = "APMotorLayout.json";
		var outputPath = "ArduPilotMotorsLayout.cs";

		var json = File.ReadAllText(jsonPath);

		var config = JsonSerializer.Deserialize<MotorConfig>(json);

		if (config == null)
		{
			Console.WriteLine("Parsing error");
			return;
		}

		var code = GenerateCode(config);
		File.WriteAllText(outputPath, code);

		Console.WriteLine($"Generated file: {outputPath}");
	}

	static string GenerateCode(MotorConfig config)
	{
		var sb = new StringBuilder();

		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("namespace YourLibrary");
		sb.AppendLine("{");

		sb.AppendLine("    public static class APMotorLayout");
		sb.AppendLine("    {");
		sb.AppendLine($"        public const string Version = \"{EscapeString(config.Version)}\";");
		sb.AppendLine();

		sb.AppendLine("        public static readonly Layout[] Layouts = new[]");
		sb.AppendLine("        {");

		foreach (var layout in config.Layouts ?? [])
		{
			sb.AppendLine("            new Layout");
			sb.AppendLine("            {");
			sb.AppendLine($"                Class = {layout.Class},");
			sb.AppendLine($"                ClassName = \"{layout.ClassName}\",");
			sb.AppendLine($"                Type = {layout.Type},");
			sb.AppendLine($"                TypeName = \"{layout.TypeName}\",");
			sb.AppendLine("                Motors = new[]");
			sb.AppendLine("                {");

			foreach (var motor in layout.Motors ?? [])
			{
				sb.AppendLine("                    new Motor");
				sb.AppendLine("                    {");
				sb.AppendLine($"                        Number = {motor.Number},");
				sb.AppendLine($"                        TestOrder = {motor.TestOrder},");
				sb.AppendLine($"                        Rotation = \"{motor.Rotation}\",");
				sb.AppendLine($"                        Roll = {FormatFloat(motor.Roll)}f,");
				sb.AppendLine($"                        Pitch = {FormatFloat(motor.Pitch)}f,");
				sb.AppendLine("                    },");
			}

			sb.AppendLine("                },");
			sb.AppendLine("            },");
		}

		sb.AppendLine("        };");
		sb.AppendLine("    }");
		sb.AppendLine("}");

		return sb.ToString();
	}

	static string FormatFloat(float value)
	{
		return value.ToString("F4", CultureInfo.InvariantCulture)
			.TrimEnd('0')
			.TrimEnd('.');
	}

	static string EscapeString(string str) => str.Replace("\"", "\\\"").Replace("\n", "\\n");

	private class MotorConfig
	{
		[JsonPropertyName("Version")]
		public string Version { get; set; } = "";

		[JsonPropertyName("layouts")]
		public List<Layout>? Layouts { get; set; }
	}

	private class Layout
	{
		[JsonPropertyName("Class")]
		public int Class { get; set; }

		[JsonPropertyName("ClassName")]
		public string ClassName { get; set; } = "";

		[JsonPropertyName("Type")]
		public int Type { get; set; }

		[JsonPropertyName("TypeName")]
		public string TypeName { get; set; } = "";

		[JsonPropertyName("motors")]
		public List<Motor>? Motors { get; set; }
	}

	private class Motor
	{
		[JsonPropertyName("Number")]
		public int Number { get; set; }

		[JsonPropertyName("TestOrder")]
		public int TestOrder { get; set; }

		[JsonPropertyName("Rotation")]
		public string Rotation { get; set; } = "";

		[JsonPropertyName("Roll")]
		public float Roll { get; set; }

		[JsonPropertyName("Pitch")]
		public float Pitch { get; set; }
	}
}